apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1 # from-param: ${replicaCount}
  selector:
    matchLabels:
      name: be
  template:
    metadata:
      labels:
        name: be
    spec:
      containers:
        - name: be
          image: be
          env:
          - name: envvar1
            value: default1 # from-param: ${application_env1}
          - name: envvar2
            value: default2 # from-param: ${application_env2}
