apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app: be-app
spec:
  replicas: 1 # from-param: ${replicaCount}
  selector:
    matchLabels:
      app: be-app
  template:
    metadata:
      labels:
        app: be-app
    spec:
      containers:
        - name: be
          image: be
          env:
          - name: envvar1
            value: default1 # from-param: ${application_env1}
          - name: envvar2
            value: default2 # from-param: ${application_env2}
