apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1
  selector:
    matchLabels:
      name: be
  template:
    metadata:
      labels:
        name: be
    spec:
      containers:
        - name: be
          image: be
