apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  selector:
    matchLabels:
      name: be
  replicas: 1
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: be
    spec:
      containers:
      - image: be
        name: be
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
          protocol: TCP