apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  labels:
    env: dev
spec:
  template:
    spec:
      containers:
      - name: fe
        env:
        - name: SITE_NAME
          value: "Demo DEV Website"