apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  labels:
    app: fe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fe
      app: fe
  template:
    metadata:
      labels:
        name: fe
        app: fe
    spec:
      containers:
        - name: fe
          image: fe
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fe
  namespace: default
spec:
  selector:
   app: fe
