# Copyright 2022 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: sabre-demo-pipeline
serialPipeline:
 stages:
 - targetId: dev
   strategy:
    standard:
      verify: true 
 - targetId: prod-multi
   deployParameters:
   - values:
       replicaCount: "2"
     matchTargetLabels:
       label1: label1
   - values:
       replicaCount: "3"
     matchTargetLabels:
       label2: label2 
       
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: dev
description: development cluster
requireApproval: false  
gke:
 cluster: projects/riccardo-blog-test-v1/locations/us-central1/clusters/devcluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
requireApproval: true
gke:
 cluster: projects/riccardo-blog-test-v1/locations/us-central1/clusters/prod-cluster1

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-multi
description: production clusters east and west
requireApproval: true
multiTarget:
  targetIds: [prod-east, prod-west]

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod-east
 labels:
   label1: label1
description: production cluster in us-east1
deployParameters:
  application_env1: "sampleValue1"
requireApproval: false
gke:
 cluster: projects/riccardo-blog-test-v1/locations/us-east1/clusters/prodcluster-useast1
 
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod-west
 labels:
   label2: label2
description: production cluster in us-west1
deployParameters:
  application_env2: "sampleValue2"
requireApproval: false
gke:
 cluster: projects/riccardo-blog-test-v1/locations/us-west1/clusters/prodcluster-uswest1

---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: sabre-demo-pipeline/promote
description: promotes a release
suspended: false
serviceAccount: 105792947502-compute@developer.gserviceaccount.com
selector:
- target:
    id: dev
rules:
- promoteRelease:
    name: "promote-release"
    wait: 1m
    toTargetId: "@next"



