apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  labels:
    app: fe
  namespace: default
spec:
  selector:
    matchLabels:
      name: fe
      app: fe
  replicas: 1
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: fe
    spec:
      containers:
      - image: fe
        name: fe
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
          protocol: TCP