apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  labels:
    app: fe-app
spec:
  selector:
    matchLabels:
      app: fe-app
  replicas: 2
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: fe-app
    spec:
      containers:
      - image: fe
        name: fe