apiVersion: v1
kind: Service
metadata:
  name: fe
  labels:
    app: fe
spec:
  ports:
  - port: 8080
    name: http
  type: LoadBalancer
  selector:
    name: be
    app: fe
  externalTrafficPolicy: Local